package moe.rukamori.archivetune.ui.player.modular

import androidx.compose.ui.graphics.vector.ImageVector
import moe.rukamori.archivetune.R

enum class PlayerComponentType(
    val id: String,
    val displayNameRes: Int,
    val previewIconRes: Int,
    val defaultWidth: Int,
    val defaultHeight: Int,
    val minWidth: Int = 1,
    val minHeight: Int = 1,
    val category: ComponentCategory = ComponentCategory.PLAYBACK,
) {
    COVER_ART(
        id = "cover_art",
        displayNameRes = R.string.cover_art,
        previewIconRes = R.drawable.album,
        defaultWidth = 4,
        defaultHeight = 4,
        category = ComponentCategory.VISUAL,
    ),
    TITLE(
        id = "title",
        displayNameRes = R.string.song_title,
        previewIconRes = R.drawable.text_fields,
        defaultWidth = 4,
        defaultHeight = 1,
        category = ComponentCategory.INFO,
    ),
    ARTIST(
        id = "artist",
        displayNameRes = R.string.artist_name,
        previewIconRes = R.drawable.artist,
        defaultWidth = 4,
        defaultHeight = 1,
        category = ComponentCategory.INFO,
    ),
    SEEK_BAR(
        id = "seek_bar",
        displayNameRes = R.string.seek_bar,
        previewIconRes = R.drawable.tune,
        defaultWidth = 4,
        defaultHeight = 1,
        category = ComponentCategory.PLAYBACK,
    ),
    TIME_DISPLAY(
        id = "time_display",
        displayNameRes = R.string.time_display,
        previewIconRes = R.drawable.timer,
        defaultWidth = 4,
        defaultHeight = 1,
        category = ComponentCategory.PLAYBACK,
    ),
    PLAY_PREVIOUS(
        id = "play_previous",
        displayNameRes = R.string.previous,
        previewIconRes = R.drawable.skip_previous,
        defaultWidth = 1,
        defaultHeight = 1,
        category = ComponentCategory.PLAYBACK,
    ),
    PLAY_PAUSE(
        id = "play_pause",
        displayNameRes = R.string.play_pause,
        previewIconRes = R.drawable.play,
        defaultWidth = 2,
        defaultHeight = 1,
        category = ComponentCategory.PLAYBACK,
    ),
    PLAY_NEXT(
        id = "play_next",
        displayNameRes = R.string.next,
        previewIconRes = R.drawable.skip_next,
        defaultWidth = 1,
        defaultHeight = 1,
        category = ComponentCategory.PLAYBACK,
    ),
    SHUFFLE(
        id = "shuffle",
        displayNameRes = R.string.shuffle,
        previewIconRes = R.drawable.shuffle,
        defaultWidth = 1,
        defaultHeight = 1,
        category = ComponentCategory.PLAYBACK,
    ),
    REPEAT(
        id = "repeat",
        displayNameRes = R.string.repeat,
        previewIconRes = R.drawable.repeat,
        defaultWidth = 1,
        defaultHeight = 1,
        category = ComponentCategory.PLAYBACK,
    ),
    LIKE(
        id = "like",
        displayNameRes = R.string.like,
        previewIconRes = R.drawable.favorite_border,
        defaultWidth = 1,
        defaultHeight = 1,
        category = ComponentCategory.ACTIONS,
    ),
    QUEUE(
        id = "queue",
        displayNameRes = R.string.queue,
        previewIconRes = R.drawable.queue_music,
        defaultWidth = 1,
        defaultHeight = 1,
        category = ComponentCategory.ACTIONS,
    ),
    LYRICS_TOGGLE(
        id = "lyrics_toggle",
        displayNameRes = R.string.lyrics,
        previewIconRes = R.drawable.lyrics,
        defaultWidth = 1,
        defaultHeight = 1,
        category = ComponentCategory.ACTIONS,
    ),
    SHARE(
        id = "share",
        displayNameRes = R.string.share,
        previewIconRes = R.drawable.share,
        defaultWidth = 1,
        defaultHeight = 1,
        category = ComponentCategory.ACTIONS,
    ),
    MORE_MENU(
        id = "more_menu",
        displayNameRes = R.string.more,
        previewIconRes = R.drawable.more_horiz,
        defaultWidth = 1,
        defaultHeight = 1,
        category = ComponentCategory.ACTIONS,
    ),
    VOLUME_SLIDER(
        id = "volume_slider",
        displayNameRes = R.string.volume,
        previewIconRes = R.drawable.volume_up,
        defaultWidth = 4,
        defaultHeight = 1,
        category = ComponentCategory.PLAYBACK,
    ),
    SLEEP_TIMER(
        id = "sleep_timer",
        displayNameRes = R.string.sleep_timer,
        previewIconRes = R.drawable.bedtime,
        defaultWidth = 1,
        defaultHeight = 1,
        category = ComponentCategory.ACTIONS,
    ),
    CANVAS_ARTWORK(
        id = "canvas_artwork",
        displayNameRes = R.string.canvas_artwork,
        previewIconRes = R.drawable.auto_awesome,
        defaultWidth = 4,
        defaultHeight = 4,
        category = ComponentCategory.VISUAL,
    ),
    EMPTY_SPACE(
        id = "empty_space",
        displayNameRes = R.string.empty_space,
        previewIconRes = R.drawable.deselect,
        defaultWidth = 1,
        defaultHeight = 1,
        category = ComponentCategory.LAYOUT,
    ),
    SPACER(
        id = "spacer",
        displayNameRes = R.string.spacer,
        previewIconRes = R.drawable.deselect,
        defaultWidth = 4,
        defaultHeight = 1,
        category = ComponentCategory.LAYOUT,
    ),
    TITLE_ARTIST(
        id = "title_artist",
        displayNameRes = R.string.title_artist,
        previewIconRes = R.drawable.artist,
        defaultWidth = 4,
        defaultHeight = 2,
        category = ComponentCategory.INFO,
    ),
}

enum class ComponentCategory {
    VISUAL,
    INFO,
    PLAYBACK,
    ACTIONS,
    LAYOUT,
}
